### PR TITLE
Final

### PR DESCRIPTION
**Pull request by bura1**
Everything is in this Final branch. 

I made two plugins. First is "wl-api" which retrieve articles from https://inshortsapi.vercel.app/news?category=science
and register custom rest route /wl/v1/articles.
Second plugin "my-articles" is gutenberg custom block. It reads api data from previous plugin and display it on frontend of website.

On the design part I did everything except slider because I am not sure should I program it myself or use some existing block from the market.

I also added database file in root directory if you need it for testing.

Here is a screenshot:
wp-task

### CODE REVIEW

**Comment by dingo-d** [comment]
Hi @bura1!

The idea was to use our boilerplate to handle all the logic, not write a separate plugin for it. I'm sorry if this was unclear from the task assignment.

We want to see how you'd use our boilerplate to create all the features in the theme since it offers lots of goodies (like WP CLI commands for creating classes, etc.).

Also, the custom block should have also been created in the theme (since all the blocks are contained in the theme), and in the next task :sweat_smile:

If it's not a huge problem, can you refactor this so that you use our boilerplate?

Oh, and don't forget to rebase once you merge first PR, that way you won't have 600+ changes in this PR (it's going to be easier for us to review).

**Comment by bura1** [comment]
Hi @dingo-d and @gabriel-glo 
I deleted my two plugins and created custom route and custom block with eightshift boilerplate. At first I didn't realize I had to create it with boilerplate. It really made things easier and faster.

I also added css in wrong place (/public/aplication.scss). Now I see that these files are automatically generated but now I have no time to change that.

First branch is rebased into main branch. I hope this is what you have been looking for.

In the meantime I discovered eightshift storybook and I tried to add a carousel to my project but after installing swiper and running "npm start" it shows this error:

```
ERROR in ./src/Blocks/assets/styles/application-blocks.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./node_modules/import-glob-loader!./src/Blocks/assets/styles/application-blocks.scss)
      Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
      SassError: Can't find stylesheet to import.
        ╷
      2 │ @import '~swiper/components/pagination/pagination.scss';
        │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        ╵
        src/Blocks/custom/carousel/carousel-style.scss 2:9     @import
        src/Blocks/assets/styles/application-blocks.scss 37:9  root stylesheet
```

As far as I can see there is 'modules' folder instead 'components' in swiper.

**Comment by gabriel-glo** [comment]
@bura1 

There seems to be an issue with the latest version of Swiper (v.7.X). Remove your current installation of swiper and install version `6.8.2`

**Comment by dingo-d** [comment]
@bura1 can you rebase this branch so that the changes that you've merged are not showing in this branch? Thanks!

**Pull request merged**
